# Generated by Django 5.1.5 on 2025-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
