# Generated by Django 5.1.5 on 2025-01-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
    ]
